import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Games Board</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="home">
        <h1 className="title">Bienvenue sur Games Board</h1>
        <p className="description">
          Le site qui vous permet de trouver des jeux de société pour vos soirées entre amis !
        </p>
        <div className="grid">
          <Link href="/games" className="card">
            <h3>Jeux de société &rarr;</h3>
            <p>Retrouvez tous les jeux de société disponibles sur le site.</p>
          </Link>
          <Link href="/about" className="card">
            <h3>À propos &rarr;</h3>
            <p>En savoir plus sur le site et son créateur.</p>
          </Link>
        </div>
      </main>
    </>
  )
}
