import {Schema, model, models} from "mongoose";

export default models.monopoly || model("monopoly", new Schema({
    id: { type: String, required: true },
    name: { type: String, required: true },
    owner: { type: String, required: true },
    users: { type: [String], required: false },
    private: { type: Boolean, required: true },
    password: { type: String, required: false },
    roomType: { type: String, required: true },
    players: { type: [{
        name: { type: String, required: true },
        position: { type: Number, required: true },
        money: { type: Number, required: true },
        chanceCardOutOfJail: { type: Boolean, required: true },
        communityChestCardOutOfJail: { type: Boolean, required: true },
        inJail: { type: Boolean, required: true },
        jailTurns: { type: Number, required: true },
        houses: { type: [{
            name: { type: String, required: true },
            color: { type: String, required: true },
            houses: { type: Number, required: true },
            hotel: { type: Boolean, required: true },
        }], required: true },
        canReRoll: { type: Boolean, required: true },
        doubleRolls: { type: Number, required: true },
    }], required: true },
    turn: { type: Number, required: true },
    started: { type: Boolean, required: true },
    finished: { type: Boolean, required: true },
    winner: { type: String, required: false },
    houses: { type: [{
        name: { type: String, required: true },
        color: { type: String, required: true },
        price: { type: Number, required: true },
        owner: { type: String, required: false },
        houses: { type: Number, required: true },
        hotel: { type: Boolean, required: true },
        hypothecated: { type: Boolean, required: true },
    }], required: true },
    chanceCards: { type: [{
        title: { type: String, required: true },
        name: { type: String, required: true },
        canBeKept: { type: Boolean, required: false, default: false },
    }], required: true },
    communityChestCards: { type: [{
        title: { type: String, required: true },
        name: { type: String, required: true },
        canBeKept: { type: Boolean, required: false, default: false },
    }], required: true },
    playerTurn: { type: String, required: true },
}));